version: '3.8'
services:
  db:
    image: postgres:13.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1312
      POSTGRES_DB: GroceryList

  test-db:
    image: postgres:13.5
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1312
      POSTGRES_DB: GroceryList
